name: manage-azure-policy-d7f9d2d9
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'AzureExport3/policies/Allowed_Location_for_move_me_resources_d2f5bb15-8bab-447a-8109-acac05f8ec88/**'
#      - 'AzureExport3/policies/Restrict_Public_IP_restrict-public-ips-policyDef/**'
#      - 'AzureExport3/initiatives/storage_account_network_restriction_policySetDef_storage-account-network-restriction-policySetDef/**'
#      - .github/workflows/manage-azure-policy-d7f9d2d9.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d7f9d2d9}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          AzureExport3/policies/Allowed_Location_for_move_me_resources_d2f5bb15-8bab-447a-8109-acac05f8ec88/**
          AzureExport3/policies/Restrict_Public_IP_restrict-public-ips-policyDef/**
          AzureExport3/initiatives/storage_account_network_restriction_policySetDef_storage-account-network-restriction-policySetDef/**
