name: manage-azure-policy-a3db9e7f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'AzureExport3/policies/Locations_allowed_828532d7-2df2-4491-8436-192da07f7c81/**'
#      - .github/workflows/manage-azure-policy-a3db9e7f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a3db9e7f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          AzureExport3/policies/Locations_allowed_828532d7-2df2-4491-8436-192da07f7c81/**
