name: manage-azure-policy-5f44fd25
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'AzureExport/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - 'AzureExport/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**'
#      - 'AzureExport/policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**'
#      - 'AzureExport/policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**'
#      - 'AzureExport/policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**'
#      - 'AzureExport/policies/SQL_managed_instances_should_use_customer-managed_keys_to_encrypt_data_at_rest_048248b0-55cd-46da-b1ff-39efd52db260/**'
#      - 'AzureExport/policies/Shared_dashboards_should_not_have_markdown_tiles_with_inline_content_04c655fe-0ac7-48ae-9a32-3a2e208c7624/**'
#      - 'AzureExport/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**'
#      - 'AzureExport/policies/Azure_API_for_FHIR_should_use_a_customer-managed_key_(CMK)_to_encrypt_data_at_rest_051cba44-2429-45b9-9649-46cec11c7119/**'
#      - 'AzureExport/policies/Deploy_Log_Analytics_agent_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**'
#      - 'AzureExport/policies/Web_Application_Firewall_(WAF)_should_be_enabled_for_Azure_Front_Door_Service service_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**'
#      - 'AzureExport/policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**'
#      - 'AzureExport/policies/Diagnostic_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**'
#      - 'AzureExport/policies/Audit_VMs_that_do_not_use_managed_disks_06a78e20-9358-41c9-923c-fb736d382a4d/**'
#      - 'AzureExport/initiatives/Audit_machines_with_insecure_password_security_settings_095e4ed9-c835-4ab6-9439-b5644362a06c/**'
#      - 'AzureExport/initiatives/HITRUST/HIPAA_a169a624-5599-4385-a696-c8d643089fab/**'
#      - 'AzureExport/initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**'
#      - 'AzureExport/initiatives/Enable_Azure_Cosmos_DB_throughput_policy_cb5e1e90-7c33-491c-a15b-24885c915752/**'
#      - 'AzureExport/initiatives/FedRAMP_High_d5264498-16f4-418a-b659-fa7ef418175f/**'
#      - .github/workflows/manage-azure-policy-5f44fd25.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5f44fd25}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          AzureExport/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
          AzureExport/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**
          AzureExport/policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**
          AzureExport/policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**
          AzureExport/policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**
          AzureExport/policies/SQL_managed_instances_should_use_customer-managed_keys_to_encrypt_data_at_rest_048248b0-55cd-46da-b1ff-39efd52db260/**
          AzureExport/policies/Shared_dashboards_should_not_have_markdown_tiles_with_inline_content_04c655fe-0ac7-48ae-9a32-3a2e208c7624/**
          AzureExport/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**
          AzureExport/policies/Azure_API_for_FHIR_should_use_a_customer-managed_key_(CMK)_to_encrypt_data_at_rest_051cba44-2429-45b9-9649-46cec11c7119/**
          AzureExport/policies/Deploy_Log_Analytics_agent_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**
          AzureExport/policies/Web_Application_Firewall_(WAF)_should_be_enabled_for_Azure_Front_Door_Service service_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**
          AzureExport/policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**
          AzureExport/policies/Diagnostic_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**
          AzureExport/policies/Audit_VMs_that_do_not_use_managed_disks_06a78e20-9358-41c9-923c-fb736d382a4d/**
          AzureExport/initiatives/Audit_machines_with_insecure_password_security_settings_095e4ed9-c835-4ab6-9439-b5644362a06c/**
          AzureExport/initiatives/HITRUST/HIPAA_a169a624-5599-4385-a696-c8d643089fab/**
          AzureExport/initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**
          AzureExport/initiatives/Enable_Azure_Cosmos_DB_throughput_policy_cb5e1e90-7c33-491c-a15b-24885c915752/**
          AzureExport/initiatives/FedRAMP_High_d5264498-16f4-418a-b659-fa7ef418175f/**
